-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ListItem exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import CustomScalarCodecs
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet CustomScalarCodecs.Id Api.Object.ListItem
id =
    Object.selectionForField "CustomScalarCodecs.Id" "id" [] (CustomScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


isHq : SelectionSet String Api.Object.ListItem
isHq =
    Object.selectionForField "String" "isHq" [] Decode.string


isResult : SelectionSet String Api.Object.ListItem
isResult =
    Object.selectionForField "String" "isResult" [] Decode.string


item :
    SelectionSet decodesTo Api.Object.Item
    -> SelectionSet decodesTo Api.Object.ListItem
item object_ =
    Object.selectionForCompositeField "item" [] object_ identity


necessaryQuantity : SelectionSet Int Api.Object.ListItem
necessaryQuantity =
    Object.selectionForField "Int" "necessaryQuantity" [] Decode.int


quantity : SelectionSet Int Api.Object.ListItem
quantity =
    Object.selectionForField "Int" "quantity" [] Decode.int
