-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ListItem exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import CustomScalarCodecs
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet (Maybe CustomScalarCodecs.Id) Api.Object.ListItem
id =
    Object.selectionForField "(Maybe CustomScalarCodecs.Id)" "id" [] (CustomScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


isHq : SelectionSet (Maybe String) Api.Object.ListItem
isHq =
    Object.selectionForField "(Maybe String)" "isHq" [] (Decode.string |> Decode.nullable)


isResult : SelectionSet (Maybe String) Api.Object.ListItem
isResult =
    Object.selectionForField "(Maybe String)" "isResult" [] (Decode.string |> Decode.nullable)


item :
    SelectionSet decodesTo Api.Object.Item
    -> SelectionSet (Maybe decodesTo) Api.Object.ListItem
item object_ =
    Object.selectionForCompositeField "item" [] object_ (identity >> Decode.nullable)


necessaryQuantity : SelectionSet (Maybe Int) Api.Object.ListItem
necessaryQuantity =
    Object.selectionForField "(Maybe Int)" "necessaryQuantity" [] (Decode.int |> Decode.nullable)


quantity : SelectionSet (Maybe Int) Api.Object.ListItem
quantity =
    Object.selectionForField "(Maybe Int)" "quantity" [] (Decode.int |> Decode.nullable)
