-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Recipe exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import CustomScalarCodecs
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


canHq : SelectionSet Bool Api.Object.Recipe
canHq =
    Object.selectionForField "Bool" "canHq" [] Decode.bool


canQuickSynth : SelectionSet Bool Api.Object.Recipe
canQuickSynth =
    Object.selectionForField "Bool" "canQuickSynth" [] Decode.bool


ingredients :
    SelectionSet decodesTo Api.Object.RecipeIngredient
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.Recipe
ingredients object_ =
    Object.selectionForCompositeField "ingredients" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


isSpecializationRequired : SelectionSet Bool Api.Object.Recipe
isSpecializationRequired =
    Object.selectionForField "Bool" "isSpecializationRequired" [] Decode.bool


patchNumber : SelectionSet Int Api.Object.Recipe
patchNumber =
    Object.selectionForField "Int" "patchNumber" [] Decode.int


requiredControl : SelectionSet Int Api.Object.Recipe
requiredControl =
    Object.selectionForField "Int" "requiredControl" [] Decode.int


requiredCraftsmanship : SelectionSet Int Api.Object.Recipe
requiredCraftsmanship =
    Object.selectionForField "Int" "requiredCraftsmanship" [] Decode.int
