-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.RecipeIngredient exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


item :
    SelectionSet decodesTo Api.Object.Item
    -> SelectionSet decodesTo Api.Object.RecipeIngredient
item object_ =
    Object.selectionForCompositeField "item" [] object_ identity


quantity : SelectionSet Int Api.Object.RecipeIngredient
quantity =
    Object.selectionForField "Int" "quantity" [] Decode.int
