-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.InputObject exposing (..)

import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import CustomScalarCodecs
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


buildCreateListInput :
    CreateListInputRequiredFields
    -> CreateListInput
buildCreateListInput required =
    { items = required.items, title = required.title }


type alias CreateListInputRequiredFields =
    { items : List (Maybe ItemInput)
    , title : String
    }


{-| Type for the CreateListInput input object.
-}
type alias CreateListInput =
    { items : List (Maybe ItemInput)
    , title : String
    }


{-| Encode a CreateListInput into a value that can be used as an argument.
-}
encodeCreateListInput : CreateListInput -> Value
encodeCreateListInput input =
    Encode.maybeObject
        [ ( "items", (encodeItemInput |> Encode.maybe |> Encode.list) input.items |> Just ), ( "title", Encode.string input.title |> Just ) ]


buildItemInput :
    ItemInputRequiredFields
    -> ItemInput
buildItemInput required =
    { id = required.id, isHq = required.isHq, quantity = required.quantity }


type alias ItemInputRequiredFields =
    { id : CustomScalarCodecs.Id
    , isHq : Bool
    , quantity : Int
    }


{-| Type for the ItemInput input object.
-}
type alias ItemInput =
    { id : CustomScalarCodecs.Id
    , isHq : Bool
    , quantity : Int
    }


{-| Encode a ItemInput into a value that can be used as an argument.
-}
encodeItemInput : ItemInput -> Value
encodeItemInput input =
    Encode.maybeObject
        [ ( "id", (CustomScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) input.id |> Just ), ( "isHq", Encode.bool input.isHq |> Just ), ( "quantity", Encode.int input.quantity |> Just ) ]


buildLoginInput :
    LoginInputRequiredFields
    -> LoginInput
buildLoginInput required =
    { email = required.email, password = required.password }


type alias LoginInputRequiredFields =
    { email : String
    , password : String
    }


{-| Type for the LoginInput input object.
-}
type alias LoginInput =
    { email : String
    , password : String
    }


{-| Encode a LoginInput into a value that can be used as an argument.
-}
encodeLoginInput : LoginInput -> Value
encodeLoginInput input =
    Encode.maybeObject
        [ ( "email", Encode.string input.email |> Just ), ( "password", Encode.string input.password |> Just ) ]


buildRegisterInput :
    RegisterInputRequiredFields
    -> RegisterInput
buildRegisterInput required =
    { email = required.email, password = required.password }


type alias RegisterInputRequiredFields =
    { email : String
    , password : String
    }


{-| Type for the RegisterInput input object.
-}
type alias RegisterInput =
    { email : String
    , password : String
    }


{-| Encode a RegisterInput into a value that can be used as an argument.
-}
encodeRegisterInput : RegisterInput -> Value
encodeRegisterInput input =
    Encode.maybeObject
        [ ( "email", Encode.string input.email |> Just ), ( "password", Encode.string input.password |> Just ) ]


buildUpdateListItemInput :
    UpdateListItemInputRequiredFields
    -> UpdateListItemInput
buildUpdateListItemInput required =
    { isHq = required.isHq, necessaryQuantity = required.necessaryQuantity, quantity = required.quantity }


type alias UpdateListItemInputRequiredFields =
    { isHq : Bool
    , necessaryQuantity : Int
    , quantity : Int
    }


{-| Type for the UpdateListItemInput input object.
-}
type alias UpdateListItemInput =
    { isHq : Bool
    , necessaryQuantity : Int
    , quantity : Int
    }


{-| Encode a UpdateListItemInput into a value that can be used as an argument.
-}
encodeUpdateListItemInput : UpdateListItemInput -> Value
encodeUpdateListItemInput input =
    Encode.maybeObject
        [ ( "isHq", Encode.bool input.isHq |> Just ), ( "necessaryQuantity", Encode.int input.necessaryQuantity |> Just ), ( "quantity", Encode.int input.quantity |> Just ) ]
