-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import CustomScalarCodecs
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreateListRequiredArguments =
    { input : Api.InputObject.CreateListInput }


{-| Create a list
-}
createList :
    CreateListRequiredArguments
    -> SelectionSet decodesTo Api.Object.List
    -> SelectionSet decodesTo RootMutation
createList requiredArgs object_ =
    Object.selectionForCompositeField "createList" [ Argument.required "input" requiredArgs.input Api.InputObject.encodeCreateListInput ] object_ identity


type alias DeleteListRequiredArguments =
    { id : CustomScalarCodecs.Id }


{-| Delete a list
-}
deleteList :
    DeleteListRequiredArguments
    -> SelectionSet decodesTo Api.Object.List
    -> SelectionSet decodesTo RootMutation
deleteList requiredArgs object_ =
    Object.selectionForCompositeField "deleteList" [ Argument.required "id" requiredArgs.id (CustomScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object_ identity


type alias LoginRequiredArguments =
    { input : Api.InputObject.LoginInput }


{-| Login
-}
login :
    LoginRequiredArguments
    -> SelectionSet decodesTo Api.Object.User
    -> SelectionSet decodesTo RootMutation
login requiredArgs object_ =
    Object.selectionForCompositeField "login" [ Argument.required "input" requiredArgs.input Api.InputObject.encodeLoginInput ] object_ identity


type alias RegisterRequiredArguments =
    { input : Api.InputObject.RegisterInput }


{-| Register a user
-}
register :
    RegisterRequiredArguments
    -> SelectionSet decodesTo Api.Object.User
    -> SelectionSet decodesTo RootMutation
register requiredArgs object_ =
    Object.selectionForCompositeField "register" [ Argument.required "input" requiredArgs.input Api.InputObject.encodeRegisterInput ] object_ identity


type alias RemoveListItemRequiredArguments =
    { id : CustomScalarCodecs.Id }


{-| Remove item from list
-}
removeListItem :
    RemoveListItemRequiredArguments
    -> SelectionSet decodesTo Api.Object.List
    -> SelectionSet decodesTo RootMutation
removeListItem requiredArgs object_ =
    Object.selectionForCompositeField "removeListItem" [ Argument.required "id" requiredArgs.id (CustomScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object_ identity


type alias UpdateListItemRequiredArguments =
    { id : CustomScalarCodecs.Id
    , input : Api.InputObject.UpdateListItemInput
    }


{-| Update item in list
-}
updateListItem :
    UpdateListItemRequiredArguments
    -> SelectionSet decodesTo Api.Object.ListItem
    -> SelectionSet decodesTo RootMutation
updateListItem requiredArgs object_ =
    Object.selectionForCompositeField "updateListItem" [ Argument.required "id" requiredArgs.id (CustomScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "input" requiredArgs.input Api.InputObject.encodeUpdateListItemInput ] object_ identity
