-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Item
    = Item


type List
    = List


type ListItem
    = ListItem


type Recipe
    = Recipe


type RecipeIngredient
    = RecipeIngredient


type User
    = User
