-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Query exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import CustomScalarCodecs
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias ItemsRequiredArguments =
    { name : String }


{-| Get a list of items
-}
items :
    ItemsRequiredArguments
    -> SelectionSet decodesTo Api.Object.Item
    -> SelectionSet (List decodesTo) RootQuery
items requiredArgs object_ =
    Object.selectionForCompositeField "items" [ Argument.required "name" requiredArgs.name Encode.string ] object_ (identity >> Decode.list)


{-| Gets the current logged in user
-}
me :
    SelectionSet decodesTo Api.Object.User
    -> SelectionSet decodesTo RootQuery
me object_ =
    Object.selectionForCompositeField "me" [] object_ identity
